template = "https://github.com/giellalt/template-lang-und"
rev_id = 295
template_sha = "9e160f410d669a53f8b740a218fd6462f17d3234"

[replacements]
__GLOTTOLOG_ID__ = "rusy1239"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-rue"
__UND2C__ = "rue"
__UNDEFINED__ = "Rusyn"
__UND__ = "rue"
