template = "https://github.com/giellalt/template-lang-und"
rev_id = 303
template_sha = "2ae3f964876faa6636309f7d609478512097ebd0"

[replacements]
__GLOTTOLOG_ID__ = "rusy1239"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-rue"
__UND2C__ = "rue"
__UNDEFINED__ = "Rusyn"
__UND__ = "rue"
