template = "https://github.com/giellalt/template-lang-und"
rev_id = 335
template_sha = "656172fb5ca68a68ee8547c7bc0cd1ce3f605fd7"

[replacements]
__GLOTTOLOG_ID__ = "rusy1239"
__LICENCE__ = "GPLv3"
__REPO__ = "lang-rue"
__UND2C__ = "rue"
__UNDEFINED__ = "Rusyn"
__UND__ = "rue"
